Attribute VB_Name = "Module95"
Sub recurly_subs_mega_macro1()

recurly_subs_rename
recurly_subs_remove_timezone
recurly_subs_period_pst
recurly_subs_activated_pst
recurly_subs_cancelled_pst
recurly_subs_expires_pst
recurly_subs_canceled
recurly_subs_expires_date
recurly_subs_activated
recurly_subs_period_ends
recurly_subs_salescycle
recurly_subs_question
recurly_subs_test_start
recurly_subs_test_next
recurly_subs_expired_tests
recurly_subs_test_overwrite
recurly_subs_email_sort
recurly_subs_reactivated_write
recurly_subs_test_overwrite
recurly_subs_order_sort
recurly_subs_finishtest_paste
recurly_subs_legit
recurly_subs_box_order1
recurly_subs_box_order2
recurly_subs_box_order3
recurly_subs_pivot
recurly_subs_copy_data
recurly_subs_chart
recurly_subs_return_to_raw
recurly_subs_pivot2
recurly_subs_copy_data2
recurly_subs_current_chart

End Sub

